server:
  port: 8080
spring:
  profiles:
    active: localhost
  application:
    name: kotlin-nuxtjs-web-application
  jackson:
    time-zone: Asia/Tokyo
allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:3000}